# Generated by Django 3.1.2 on 2020-10-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='file_name',
            new_name='anime_mal_code',
        ),
    ]
