# Generated by Django 3.1.2 on 2020-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201025_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_mal_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='ident',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
