# Generated by Django 3.1.2 on 2020-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20201025_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_mal_code',
            field=models.TextField(null=True),
        ),
    ]
