# Generated by Django 3.1.2 on 2020-11-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20201103_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_acc',
            field=models.IntegerField(default=0),
        ),
    ]
