# Generated by Django 3.1.2 on 2020-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_user_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateField(default=None, null=True),
        ),
    ]
