# Generated by Django 3.1.2 on 2020-11-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20201110_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_modified',
            new_name='signup_date',
        ),
    ]
