# Generated by Django 3.1.2 on 2020-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20201110_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ex_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_date',
            field=models.DateField(default=None),
        ),
    ]
