# Generated by Django 3.1.2 on 2020-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_user_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user_id', models.IntegerField()),
                ('ex_date', models.DateField()),
            ],
        ),
    ]
