# Generated by Django 3.1.2 on 2020-12-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_auth',
            old_name='ex_date',
            new_name='token_ex',
        ),
    ]
