# Generated by Django 3.1.2 on 2020-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20201204_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_email',
            field=models.BooleanField(default=False),
        ),
    ]
