# Generated by Django 3.1.4 on 2020-12-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_user_valid_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Descrição do usuario'),
        ),
    ]
