# Generated by Django 3.1.4 on 2020-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField()),
                ('engine', models.CharField(default='Unkown', max_length=15)),
                ('mal_code', models.IntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
