# Generated by Django 3.1.4 on 2020-12-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
